apiVersion: v1
kind: Service
metadata:
  name: {{ include "elasticsearch.discovery.fullname" . }}
  labels: {{- include "elasticsearch.labels" . | nindent 4 }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 9300
      name: transport
      targetPort: transport
  publishNotReadyAddresses: true
  sessionAffinity: None
  selector: {{- include "elasticsearch.matchLabels" . | nindent 4 }}
