{{- if and .Values.curator.enabled .Values.curator.serviceAccount.create .Values.curator.rbac.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "elasticsearch.curator.serviceAccountName" . }}
  labels: {{- include "elasticsearch.labels" . | nindent 4 }}
    role: curator
{{- end }}
---
{{- if .Values.data.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "elasticsearch.data.serviceAccountName" . }}
  labels: {{- include "elasticsearch.labels" . | nindent 4 }}
    role: data
{{- end }}
---
{{- if .Values.master.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "elasticsearch.master.serviceAccountName" . }}
  labels: {{- include "elasticsearch.labels" . | nindent 4 }}
    role: master
{{- end }}
---
{{- if .Values.coordinating.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "elasticsearch.coordinating.serviceAccountName" . }}
  labels: {{- include "elasticsearch.labels" . | nindent 4 }}
    role: coordinating-only
{{- end }}
